name: Build & Publish Artifacts

on:
 push:
   branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check
      uses: actions/checkout@v2
    - name: Setup JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Gradle Build
      run: |
        chmod +x ./gradlew
        ./gradlew build --scan
    - name: Get APK
      id: apk-path
      run: |
        path=$(find ${{github.workspace}}/android/build/outputs/apk -name '*.apk' -type f | head -1)
        echo "::set-output name=path::$path"
    - name: Get Jar
      id: jar-path
      run: |
        path=$(find ${{github.workspace}}/desktop/build/distributions/ -name '*.zip' -type f | head -1)
        echo "::set-output name=path::$path"
    - name: Publish Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Outputs
        path: |
          ${{ steps.apk-path.outputs.path }}
          ${{ steps.jar-path.outputs.path }}
