name: Build & Publish Artifacts

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check
      uses: actions/checkout@v2
    - name: Setup JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Gradle Build
      run: |
        chmod +x ./gradlew
        ./gradlew build --scan
    - name: Get Path
      id: path
      run: |
        path0=$(find ${{github.workspace}}/android/build/outputs/apk -name '*.apk' -type f | head -1)
        echo "::set-output name=path0::$path0"
        path1=$(find ${{github.workspace}}/desktop/build/distributions/ -name '*.zip' -type f | head -1)
        echo "::set-output name=path1::$path1"
    - name: Publish Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: outputs
        path: |
          ${{ steps.path.outputs.path0 }}
          ${{ steps.path.outputs.path1 }}
