name: Build & Publish Release APK

on:
 push:
   branch:
     - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Make Gradle executable
      run: chmod +x ./gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Build Release APK
      run: ./gradlew assembleRelease
    - name: Get apk path
      id: apk-path
      run: |
        path=$(find ${{github.workspace}}/android/build/outputs/apk -name '*.apk' -type f | head -1)
        echo "::set-output name=path::$path"
    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: App
        path: ${{ steps.apk-path.outputs.path }}

