name: Build & Publish Android Artifacts

on:
 push:
   paths:
    - 'android/**'
    - 'core/**'
    - 'native-core/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check
      uses: actions/checkout@v3
    - name: Setup JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: 'gradle'
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2.3.0
      with:
        gradle-version: 6.1.1
    - name: Build Gradle
      run: gradle :android:build
    - name: Get APK
      id: apk-path
      run: |
        path=$(find ${{github.workspace}}/android/build/outputs/apk -name '*.apk' -type f | head -1)
        echo "::set-output name=path::$path"
    - name: Publish Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Android-Output
        path: ${{ steps.apk-path.outputs.path }}
