name: 'Clean Up'

on: workflow_dispatch

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - name: Purge artifacts
        uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          expire-in: 1days
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2.0.3
        with:
          retain_days: 0
          keep_minimum_runs: 1
