name: 'Clean Up'

on: workflow_dispatch

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Actions Cleaner
        uses: rokibhasansagar/slimhub_actions@v3
      - name: GitHub Actions Artifact Cleaner
        uses: glassechidna/artifact-cleaner@v2
        with:
          minimumAge: 360
