name: 'Clean Up'

on: workflow_dispatch

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - name: Clean up previous workflow runs
        uses: egmacke/action-cleanup-workflow-runs@v1.2
        with:
          retain: 1
